USE [master]
GO

/****** Object:  Database [Books]    Script Date: 14/01/2017 13:34:35 ******/
CREATE DATABASE [Books]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Books', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Books.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Books_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Books_log.ldf' , SIZE = 3072KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Books] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Books].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Books] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Books] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Books] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Books] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Books] SET ARITHABORT OFF 
GO

ALTER DATABASE [Books] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Books] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Books] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Books] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Books] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Books] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Books] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Books] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Books] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Books] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Books] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Books] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Books] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Books] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Books] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Books] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Books] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Books] SET RECOVERY FULL 
GO

ALTER DATABASE [Books] SET  MULTI_USER 
GO

ALTER DATABASE [Books] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Books] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Books] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Books] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Books] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Books] SET  READ_WRITE 
GO


